services:
  db:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    env_file:
      - .env
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2180:2181"
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka:latest
    env_file:
      - .env
    ports:
      - "9090:9092"
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - kafka

volumes:
  pg-data: