services:
  db:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    env_file:
      - .env

  migrations:
    build: .
    env_file:
      .env
    volumes:
      - './:/app'
    command: sh -c "sleep 5s && alembic upgrade head"
    depends_on:
      - db

  app:
    build: .
    volumes:
      - './:/app'
    env_file:
      - .env
    command: sh -c "uvicorn src.main:app --reload  --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      kafka:
        condition: service_healthy
      migrations:
        condition: service_started
      

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - kafka-data:/var/lib/kafka/data
    env_file:
      - .env
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5


volumes:
  pg-data:
  kafka-data: