services:
  db:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    env_file:
      - .env

  migrations:
    build: .
    env_file:
      .env
    volumes:
      - './:/app'
    command: sh -c "sleep 5s && alembic upgrade head"
    depends_on:
      - db

  app:
    build: .
    env_file:
      - .env
    command: sh -c "uvicorn src.main:app --reload  --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - migrations
      - kafka
      

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - kafka-data:/var/lib/kafka/data
    env_file:
      - .env
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - kafka

volumes:
  pg-data:
  kafka-data: